#include <D2DataTbls.h>
#include <DataTbls/SequenceTbls.h>
#include <D2BitManip.h>
#include <Units/Units.h>
#include <D2Skills.h>
#include <D2Composit.h>

//D2Common.0x6FDDE6A8
struct D2AnimSeqTxt gPlayerSequenceHandToHand1[13] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDE6F8
struct D2AnimSeqTxt gPlayerSequenceHandToHand2[14] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDE750
struct D2AnimSeqTxt gPlayerSequenceJab_BOW[18] =
{
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_PLAY_SOUND },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_PLAY_SOUND },
	{ 0, PLRMODE_ATTACK2, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_PLAY_SOUND },
	{ 0, PLRMODE_ATTACK2, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDE7C0
struct D2AnimSeqTxt gPlayerSequenceJab_1HS[21] =
{
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_PLAY_SOUND },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_PLAY_SOUND },
	{ 0, PLRMODE_ATTACK2, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_PLAY_SOUND },
	{ 0, PLRMODE_ATTACK2, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK2, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 15, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDE840
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceJab =
{
	gPlayerSequenceHandToHand1, 13, 13,
	gPlayerSequenceJab_BOW, 18, 18,
	gPlayerSequenceJab_1HS, 21, 21,
};

//D2Common.0x6FDDE8E8
struct D2AnimSeqTxt gPlayerSequenceSacrifice_1HT[7] =
{
	{ 0, PLRMODE_ATTACK2, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK2, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDE914
struct D2AnimSeqTxt gPlayerSequenceSacrifice_STF[8] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDE948
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceSacrifice =
{
	gPlayerSequenceHandToHand2, 14, 14,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceSacrifice_1HT, 7, 7,
	gPlayerSequenceSacrifice_STF, 8, 8,
};

//D2Common.0x6FDDE9F0
struct D2AnimSeqTxt gPlayerSequenceChastise_1HT[16] =
{
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK2, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDEA50
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceChastise =
{
	gPlayerSequenceHandToHand2, 14, 14,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceChastise_1HT, 16, 16,
};

//D2Common.0x6FDDEAF8
struct D2AnimSeqTxt gPlayerSequenceCharge[15] =
{
	{ 0, PLRMODE_RUN, 0, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_RUN, 1, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_RUN, 2, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_RUN, 3, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_RUN, 4, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_RUN, 5, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_RUN, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_RUN, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_PLAY_SOUND },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDEB58
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceCharge =
{
	gPlayerSequenceCharge, 15, 15,
	gPlayerSequenceCharge, 15, 15,
	gPlayerSequenceCharge, 15, 15,
	gPlayerSequenceCharge, 15, 15,
	gPlayerSequenceCharge, 15, 15,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceCharge, 15, 15,
};

//D2Common.0x6FDDEC00
struct D2AnimSeqTxt gPlayerSequenceDefiance_1HT[6] =
{
	{ 0, PLRMODE_ATTACK2, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK2, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 12, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDEC28
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceDefiance =
{
	gPlayerSequenceHandToHand2, 14, 14,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceDefiance_1HT, 6, 6,
};

//D2Common.0x6FDDECD0
struct D2AnimSeqTxt gPlayerSequenceInferno[15] =
{
	{ 0, PLRMODE_CAST, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_CAST, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDED30
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceInferno =
{
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
	gPlayerSequenceInferno, 15, 15,
};

//D2Common.0x6FDDEDD8
struct D2AnimSeqTxt gPlayerSequenceStrafe_2HS[13] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDEE28
struct D2AnimSeqTxt gPlayerSequenceStrafe_2HT[20] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 16, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 17, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 18, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 19, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDEEA0
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceStrafe =
{
	gPlayerSequenceHandToHand1, 13, 13,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceStrafe_2HS, 13, 13,
	gPlayerSequenceStrafe_2HT, 20, 20,
};

//D2Common.0x6FDDEF48
struct D2AnimSeqTxt gPlayerSequenceImpale_BOW[21] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDEFC8
struct D2AnimSeqTxt gPlayerSequenceImpale_1HS[24] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 16, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 17, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF058
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceImpale =
{
	gPlayerSequenceHandToHand1, 13, 13,
	gPlayerSequenceImpale_BOW, 21, 21,
	gPlayerSequenceImpale_1HS, 24, 24,
};

//D2Common.0x6FDDF100
struct D2AnimSeqTxt gPlayerSequenceFend_BOW[16] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 12, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF160
struct D2AnimSeqTxt gPlayerSequenceFend_1HS[16] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 16, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 17, 0, ANIMSEQ_EVENT_NONE },
	{ 0, 0, 0, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF1C0
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceFend =
{
	gPlayerSequenceHandToHand1, 13, 13,
	gPlayerSequenceFend_BOW, 16, 16,
	gPlayerSequenceFend_1HS, 16, 16,
};

//D2Common.0x6FDDF268
struct D2AnimSeqTxt gPlayerSequenceWhirlwind[8] =
{
	{ 0, PLRMODE_ATTACK1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
};

//D2Common.0x6FDDF298
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceWhirlwind =
{
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
	gPlayerSequenceWhirlwind, 8, 8,
};

//D2Common.0x6FDDF340
struct D2AnimSeqTxt gPlayerSequenceDoubleSwing[17] =
{
	{ 0, PLRMODE_ATTACK1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 2, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL3, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 11, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF3A8
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceDoubleSwing =
{
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
	gPlayerSequenceDoubleSwing, 17, 17,
};

//D2Common.0x6FDDF450
struct D2AnimSeqTxt gPlayerSequenceLightning[19] =
{
	{ 0, PLRMODE_CAST, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF4C8
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceLightning =
{
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
	gPlayerSequenceLightning, 19, 19,
};

//D2Common.0x6FDDF570
struct D2AnimSeqTxt gPlayerSequenceLeap[15] =
{
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 14, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
};

//D2Common.0x6FDDF5D0
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceLeap =
{
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
	gPlayerSequenceLeap, 15, 15,
};

//D2Common.0x6FDDF678
struct D2AnimSeqTxt gPlayerSequenceLeapAttack_HTH[22] =
{
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF700
struct D2AnimSeqTxt gPlayerSequenceLeapAttack_BOW_1HT[25] =
{
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF798
struct D2AnimSeqTxt gPlayerSequenceLeapAttack_1HS_XBW[28] =
{
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 16, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 17, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 18, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF840
struct D2AnimSeqTxt gPlayerSequenceLeapAttack_STF[27] =
{
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 8, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 16, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK1, 17, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF8E8
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceLeapAttack =
{
	gPlayerSequenceLeapAttack_HTH, 22, 22,
	gPlayerSequenceLeapAttack_BOW_1HT, 25, 25,
	gPlayerSequenceLeapAttack_1HS_XBW, 28, 28,
	gPlayerSequenceLeapAttack_BOW_1HT, 25, 25,
	gPlayerSequenceLeapAttack_STF, 27, 27,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceLeapAttack_1HS_XBW, 28, 28,
	gPlayerSequenceLeapAttack_HTH, 22, 22,
	gPlayerSequenceLeapAttack_HTH, 22, 22,
	gPlayerSequenceLeapAttack_HTH, 22, 22,
	gPlayerSequenceLeapAttack_HTH, 22, 22,
	gPlayerSequenceLeapAttack_HTH, 22, 22,
	gPlayerSequenceLeapAttack_HTH, 22, 22,
};

//D2Common.0x6FDDF990
struct D2AnimSeqTxt gPlayerSequenceDoubleThrow[12] =
{
	{ 0, PLRMODE_THROW, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_THROW, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_THROW, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_THROW, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_THROW, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_THROW, 8, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL3, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL3, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL3, 10, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDF9D8
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceDoubleThrow =
{
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
	gPlayerSequenceDoubleThrow, 12, 12,
};

//D2Common.0x6FDDFA80
struct D2AnimSeqTxt gPlayerSequenceDragonClaw_HTH_HT1[12] =
{
	{ 0, PLRMODE_ATTACK2, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_ATTACK2, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 11, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDFAC8
struct D2AnimSeqTxt gPlayerSequenceDragonClaw_HT2[16] =
{
	{ 0, PLRMODE_ATTACK2, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_ATTACK2, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL4, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL4, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL4, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL4, 6, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL4, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL4, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL4, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL4, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL4, 11, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDFB28
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceDragonClaw =
{
	gPlayerSequenceDragonClaw_HTH_HT1, 12, 12,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceDragonClaw_HTH_HT1, 12, 12,
	gPlayerSequenceDragonClaw_HT2, 16, 16,
};

//D2Common.0x6FDDFBD0
struct D2AnimSeqTxt gPlayerSequenceProjection[19] =
{
	{ 0, PLRMODE_CAST, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 7, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_CAST, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 11, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_CAST, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 16, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 17, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 18, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, 0, 0, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDFC48
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceProjection =
{
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceProjection, 19, 19,
	gPlayerSequenceProjection, 19, 19,
};

//D2Common.0x6FDDFCF0
struct D2AnimSeqTxt gPlayerSequenceDragonTalon[20] =
{
	{ 0, PLRMODE_KICK, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 4, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_KICK, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 4, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_KICK, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 5, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_KICK, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 11, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDFD68
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceDragonTalon =
{
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceDragonTalon, 20, 20,
	gPlayerSequenceDragonTalon, 20, 20,
};

//D2Common.0x6FDDFE10
struct D2AnimSeqTxt gPlayerSequenceArcticBlast[15] =
{
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDFE70
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceArcticBlast =
{
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
	gPlayerSequenceArcticBlast, 15, 15,
};

//D2Common.0x6FDDFF18
struct D2AnimSeqTxt gPlayerSequenceDragonBreath[17] =
{
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 14, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDDFF80
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceDragonBreath =
{
	gPlayerSequenceDragonBreath, 17, 17,
	gPlayerSequenceDragonBreath, 17, 17,
	gPlayerSequenceDragonBreath, 17, 17,
	gPlayerSequenceDragonBreath, 17, 17,
	gPlayerSequenceDragonBreath, 17, 17,
	gPlayerSequenceDragonBreath, 17, 17,
	gPlayerSequenceDragonBreath, 17, 17,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	0, 0, 0,
	gPlayerSequenceDragonBreath, 17, 17,
	gPlayerSequenceDragonBreath, 17, 17,
};

//D2Common.0x6FDE0028
struct D2AnimSeqTxt gPlayerSequenceDragonFlight[23] =
{
	{ 0, PLRMODE_CAST, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_KICK, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 4, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_KICK, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_KICK, 12, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDE00B8
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceDragonFlight =
{
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
	gPlayerSequenceDragonFlight, 23, 23,
};

//D2Common.0x6FDE0160
struct D2AnimSeqTxt gPlayerSequenceUnmorph[16] =
{
	{ 0, PLRMODE_SPECIAL1, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 10, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 2, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_SPECIAL1, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_SPECIAL1, 0, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDE01C0
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceUnmorph =
{
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
	gPlayerSequenceUnmorph, 16, 16,
};

//D2Common.0x6FDE0268
struct D2AnimSeqTxt gPlayerSequenceBladeFury[19] =
{
	{ 0, PLRMODE_CAST, 0, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 1, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 2, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 3, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 4, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 5, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 6, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 7, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 8, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 9, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 10, 0, ANIMSEQ_EVENT_MELEE_ATTACK },
	{ 0, PLRMODE_CAST, 11, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 12, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 13, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 14, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 15, 0, ANIMSEQ_EVENT_NONE },
	{ 0, PLRMODE_CAST, 16, 0, ANIMSEQ_EVENT_NONE },
};

//D2Common.0x6FDE02E0
struct D2PlayerWeaponSequences gPlayerWeaponsSequenceBladeFury =
{
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
	gPlayerSequenceBladeFury, 19, 19,
};

//D2Common.0x6FDE0388
struct D2PlayerWeaponSequences* gPlayerWeaponsSequenceTable[24] =
{
	NULL,
	&gPlayerWeaponsSequenceJab,
	&gPlayerWeaponsSequenceSacrifice,
	&gPlayerWeaponsSequenceChastise,
	&gPlayerWeaponsSequenceCharge,
	&gPlayerWeaponsSequenceDefiance,
	&gPlayerWeaponsSequenceInferno,
	&gPlayerWeaponsSequenceStrafe,
	&gPlayerWeaponsSequenceImpale,
	&gPlayerWeaponsSequenceFend,
	&gPlayerWeaponsSequenceWhirlwind,
	&gPlayerWeaponsSequenceDoubleSwing,
	&gPlayerWeaponsSequenceLightning,
	&gPlayerWeaponsSequenceLeap,
	&gPlayerWeaponsSequenceLeapAttack,
	&gPlayerWeaponsSequenceDoubleThrow,
	&gPlayerWeaponsSequenceDragonClaw,
	&gPlayerWeaponsSequenceProjection,
	&gPlayerWeaponsSequenceArcticBlast,
	&gPlayerWeaponsSequenceDragonTalon,
	&gPlayerWeaponsSequenceDragonBreath,
	&gPlayerWeaponsSequenceDragonFlight,
	&gPlayerWeaponsSequenceUnmorph,
	&gPlayerWeaponsSequenceBladeFury,
};

//D2Common.0x6FDE03E8
//Note: This should really just be an array since the indices are ordered anyway...
static const int gWeaponIndexToClassMap[NUM_WEAPON_CLASSES][2] =
{
	{ 0, WEAPONCLASS_HTH },
	{ 1, WEAPONCLASS_1HT },
	{ 2, WEAPONCLASS_2HT },
	{ 3, WEAPONCLASS_1HS },
	{ 4, WEAPONCLASS_2HS },
	{ 5, WEAPONCLASS_BOW },
	{ 6, WEAPONCLASS_XBW },
	{ 7, WEAPONCLASS_STF },
	{ 8, WEAPONCLASS_1JS },
	{ 9, WEAPONCLASS_1JT },
	{ 10, WEAPONCLASS_1SS },
	{ 11, WEAPONCLASS_1ST },
	{ 12, WEAPONCLASS_HT1 },
	{ 13, WEAPONCLASS_HT2 }
};



//D2Common.0x6FD727A0 (#10682)
struct D2AnimSeqTxt* __cdecl DATATBLS_GetMonSeqTxtRecordFromUnit(struct D2Unit* pUnit)
{
	struct D2AnimSeqRecord* pSeqRecord = DATATBLS_GetSeqRecordFromUnit(pUnit);
	if (pSeqRecord)
	{
		return pSeqRecord->pAnimSeqTxtRecord;
	}

	return NULL;
}

//D2Common.0x6FD727C0
struct D2AnimSeqRecord* __cdecl DATATBLS_GetSeqRecordFromUnit(struct D2Unit* pUnit)
{
	struct D2Skill* pSkill = UNITS_GetUsedSkill(pUnit);
	if (pSkill)
	{
		int nSequenceNum = SKILLS_GetSeqNumFromSkill(pUnit, pSkill);

		if (nSequenceNum > 0)
		{
			int nUnitType = UNIT_TYPES_COUNT;
			if (pUnit)
			{
				nUnitType = pUnit->dwUnitType;
			}

			if (nUnitType == UNIT_PLAYER)
			{
				int nWeaponClass = WEAPONCLASS_HTH;
				COMPOSIT_GetWeaponClassId(pUnit, pUnit->pInventory, &nWeaponClass, -1, TRUE);

				int nWClassIndex = -1;
				for (int i = 0; i < NUM_WEAPON_CLASSES; i++)
				{
					if (nWeaponClass == gWeaponIndexToClassMap[i][1])
					{
						nWClassIndex = gWeaponIndexToClassMap[i][0];
						break;
					}
				}

				D2_ASSERT(nWClassIndex != -1);

				return &gPlayerWeaponsSequenceTable[nSequenceNum]->weaponRecords[nWClassIndex];
			}
			else if (nUnitType == UNIT_MONSTER && DATATBLS_GetMonStatsTxtRecord(pUnit->dwClassId))
			{
				return DATATBLS_GetMonSeqTableRecord(nSequenceNum);
			}
		}
	}

	return nullptr;
}

//D2Common.0x6FD728A0 (#10683)
int __cdecl DATATBLS_GetSeqFramePointsCount(struct D2Unit* pUnit)
{
	struct D2AnimSeqRecord* pSeqRecord = DATATBLS_GetSeqRecordFromUnit(pUnit);
	if (pSeqRecord)
	{
		return (pSeqRecord->nSeqFramesCount << 8);
	}

	return 0;
}

//D2Common.0x6FD728C0 (#10684)
int __cdecl DATATBLS_GetSeqFrameCount(struct D2Unit* pUnit)
{
	struct D2AnimSeqRecord* pSeqRecord = DATATBLS_GetSeqRecordFromUnit(pUnit);
	if (pSeqRecord)
	{
		return pSeqRecord->nFramesCount;
	}

	return 0;
}

//D2Common.0x6FD728E0 (#10685)
void __cdecl DATATBLS_ComputeSequenceAnimation(struct D2AnimSeqTxt* pMonSeqTxt, int nTargetFramePoint, int nCurrentFramePoint, unsigned int* pMode, unsigned int* pFrame, int* pDirection, int* pEvent)
{
	if (pMonSeqTxt)
	{
		const struct D2AnimSeqTxt* pMonSeqTxtRecord = &pMonSeqTxt[nTargetFramePoint >> 8];

		*pMode = pMonSeqTxtRecord->nMode;
		*pFrame = pMonSeqTxtRecord->nFrame;
		*pDirection = pMonSeqTxtRecord->nDir;

		if (nCurrentFramePoint == nTargetFramePoint)
		{
			*pEvent = pMonSeqTxtRecord->nEvent;
		}
		else // Retrieve the last event, note that it discard the intermediary events.
		{
			*pEvent = 0;
			const int nNextFrame = (nCurrentFramePoint >> 8) + 1;
			const int nTargetFrame = nTargetFramePoint >> 8;
			for (int frameIdx = nNextFrame; frameIdx <= nTargetFrame; frameIdx++)
			{
				const enum D2AnimSeqEvent nEvent = pMonSeqTxt[frameIdx].nEvent;
				if (nEvent != ANIMSEQ_EVENT_NONE)
				{
					*pEvent = nEvent;
				}
			}
		}
	}
	else
	{
		*pMode = 0;
		*pFrame = 0;
		*pDirection = 0;
		*pEvent = ANIMSEQ_EVENT_NONE;
	}
}

//D2Common.0x6FD72990 (#10686)
void __cdecl DATATBLS_GetSequenceEvent(struct D2AnimSeqTxt* pMonSeqTxt, int nSeqFramePoint, int* pEvent)
{
	if (pMonSeqTxt)
	{
		*pEvent = pMonSeqTxt[nSeqFramePoint >> 8].nEvent;
	}
	else
	{
		*pEvent = 0;
	}
}

//D2Common.0x6FD6F050
void __cdecl DATATBLS_LoadMonSeqTxt(HD2ARCHIVE hArchive)
{
	struct D2BinField pTbl[] =
	{
		{ "sequence", TXTFIELD_NAMETOINDEX, 0, 0, &sgptDataTables->pMonSeqLinker },
		{ "mode", TXTFIELD_CODETOBYTE, 0, 2, &sgptDataTables->pMonModeLinker },
		{ "frame", TXTFIELD_BYTE, 0, 3, NULL },
		{ "dir", TXTFIELD_BYTE, 0, 4, NULL },
		{ "event", TXTFIELD_BYTE, 0, 5, NULL },
		{ "end", TXTFIELD_NONE, 0, 0, NULL },
	};

	sgptDataTables->pMonSeqLinker = (struct D2TxtLink*)FOG_AllocLinker(__FILE__, __LINE__);
	sgptDataTables->pMonSeqTxt = (struct D2AnimSeqTxt*)DATATBLS_CompileTxt(hArchive, "monseq", pTbl, &sgptDataTables->nMonSeqTxtRecordCount, sizeof(struct D2AnimSeqTxt));

	if (sgptDataTables->nMonSeqTxtRecordCount > 0)
	{
		sgptDataTables->nMonSeqTableRecordCount = sgptDataTables->pMonSeqTxt[sgptDataTables->nMonSeqTxtRecordCount - 1].wSequence + 1;
		sgptDataTables->pMonSeqTable = (struct D2AnimSeqRecord*)D2_CALLOC_POOL(NULL, sizeof(struct D2AnimSeqRecord) * sgptDataTables->nMonSeqTableRecordCount);
		
		for (int i = 0; i < sgptDataTables->nMonSeqTxtRecordCount; ++i)
		{
			int nSequence = sgptDataTables->pMonSeqTxt[i].wSequence;
			if (!sgptDataTables->pMonSeqTable[nSequence].pAnimSeqTxtRecord)
			{
				sgptDataTables->pMonSeqTable[nSequence].pAnimSeqTxtRecord = &sgptDataTables->pMonSeqTxt[i];
			}

			++sgptDataTables->pMonSeqTable[nSequence].nSeqFramesCount;
			++sgptDataTables->pMonSeqTable[nSequence].nFramesCount;
		}
	}
}

//D2Common.0x6FD6F200 (#11262)
struct D2AnimSeqRecord* __cdecl DATATBLS_GetMonSeqTableRecord(int nSequence)
{
	if (nSequence >= 0 && nSequence < sgptDataTables->nMonSeqTableRecordCount)
	{
		return &sgptDataTables->pMonSeqTable[nSequence];
	}

	return NULL;
}